mode: "sar"
vocab_size: 10000
checkpoint_dir: "./checkpoints"

max_seq_len: 128
batch_size: 32
num_train_steps: 4000

eval_every: 100
save_every: 100

lr: 0.0003

compress_seq_len: 4
dim_embed: 256
dim_ffn: 768

n_layer: 8
n_head: 8

eval_num_batches: 16
