mode: "base"
vocab_size: 10000
checkpoint_dir: "./checkpoints"

max_length: 256
batch_size: 512
num_train_steps: 32000
eval_every: 100
save_every: 1000

lr: 0.001
eval_num_batches: 4

n_embed: 256
n_layer: 8
n_head: 16