mode: "overlap"
vocab_size: 10000
checkpoint_dir: "./checkpoints"

max_length: 256
batch_size: 128
num_train_steps: 32000
num_warmup_steps: 1000
eval_every: 500
save_every: 1000

lr: 0.0001

k: 8
p_extend: 0.5
extend_k: 4

eval_num_batches: 4

n_embed: 256
n_layer: 8
n_head: 16