mode: "sar"
vocab_size: 10000
checkpoint_dir: "./checkpoints"

max_length: 128
batch_size: 32
num_train_steps: 32000
eval_every: 100
save_every: 1000

lr: 0.0001

k: 8

eval_num_batches: 4

n_embed: 128
n_layer: 4
n_head: 8